---
- hosts: myhosts
  connection: local
  name: Disable PXE in NICs
  gather_facts: False

  # Updating BIOS settings requires creating a configuration job to implement,
  # which then reboots the system if the BIOS attribute was updated.

  vars:
  - attribute_name: PxeDev2EnDis
  - attribute_value: Disabled

  tasks:

  - name: Set {{ attribute_name }} to {{ attribute_value }}
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attr_name: "{{ attribute_name }}"
      bios_attr_value: "{{ attribute_value }}"
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
    register: bios_attribute

  - name: Schedule Config Job - Reboot
    redfish_command:
      category: Systems
      command: CreateBiosConfigJob
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
    when: bios_attribute.changed
