---
- hosts: myhosts
  connection: local
  name: Disable PXE in NICs
  gather_facts: False

  # Updating BIOS settings requires creating a configuration job to implement,
  # which then reboots the system. You can choose to reboot here or at a later 
  # time. To reboot immediately, uncomment the last task.

  tasks:

  - name: Disable PXE Boot for NIC1
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attr_name: PxeDev1EnDis
      bios_attr_value: Disabled
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"

  - name: Schedule Config Job - Reboot
    redfish_command:
      category: Systems
      command: CreateBiosConfigJob
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
