---
- hosts: myhosts
  connection: local
  name: Set BIOS attribute - choose below
  gather_facts: False

  # Updating BIOS settings requires creating a configuration job to implement,
  # which then reboots the system.

  # BIOS attributes that have been tested
  #
  # Name			Value
  # --------------------------------------------------
  # OsWatchdogTimer		Disabled / Enabled
  # ProcVirtualization		Disabled / Enabled
  # MemTest			Disabled / Enabled
  # SriovGlobalEnable		Disabled / Enabled

  vars:
  - attribute_name1: SriovGlobalEnable
  - attribute_value1: Disabled
  - attribute_name2: ProcVirtualization
  - attribute_value2: Enabled

  tasks:

  - name: Set BIOS attribute {{ attribute_name1 }} to {{ attribute_value1 }}
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attr_name: "{{ attribute_name1 }}"
      bios_attr_value: "{{ attribute_value1 }}"
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"

  - name: Set BIOS attribute {{ attribute_name2 }} to {{ attribute_value2 }}
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attr_name: "{{ attribute_name2 }}"
      bios_attr_value: "{{ attribute_value2 }}"
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"

  - name: Schedule Config Job - Reboot
    redfish_command:
      category: Systems
      command: CreateBiosConfigJob
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
