---
- hosts: myhosts
  connection: local
  name: Set one-time BIOS boot device
  gather_facts: False

  # Bootdevice options include: None, Pxe, Cd, Floppy, Hdd, BiosSetup,
  # Utilities, UefiTarget & SDCard. Only works in Legacy BIOS mode.

  vars:
    - bootdevice: Pxe

  tasks:

  - name: Set one-time boot device to {{ bootdevice }}
    redfish_command:
      category: Systems
      command: SetOneTimeBoot
      bootdevice: "{{ bootdevice }}"
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: bios_onetimeboot

  - name: Reboot system
    redfish_command:
      category: Systems
      command: PowerGracefulRestart
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    when: bios_onetimeboot.changed
