---
- hosts: myhosts
  connection: local
  name: Set boot mode to Legacy BIOS and reboot
  gather_facts: False

  # Updating BIOS settings requires creating a configuration job to implement,
  # which then reboots the system if the BIOS attribute was updated.

  vars:
  - attribute_name: BootMode
  - attribute_value: Bios

  tasks:

  - name: Set {{ attribute_name }} to {{ attribute_value }}
    redfish_config:
      category: Systems
      command: SetBiosAttributes
      bios_attr_name: "{{ attribute_name }}"
      bios_attr_value: "{{ attribute_value }}"
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
    register: bios_attribute

  - name: Create BIOS configuration job (schedule BIOS setting update)
    redfish_command:
      category: Systems
      command: CreateBiosConfigJob
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
    when: bios_attribute.changed

  - name: Reboot system to apply new BIOS settings
    redfish_command:
      category: Systems
      command: PowerGracefulRestart
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
    when: bios_attribute.changed

