---
- hosts: myhosts
  connection: local
  name: Set default BIOS settings
  gather_facts: False

  tasks:

  - name: Set default settings
    redfish:
      category: System
      command: SetBiosDefaultSettings
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
