---
- hosts: myhosts
  name: Set BIOS attribute - choose one below
  gather_facts: False

  # BIOS attributes that have been tested
  #
  # Name			Value
  # --------------------------------------------------
  # OsWatchdogTimer		Disabled / Enabled
  # ProcVirtualization		Disabled / Enabled
  # MemTest			Disabled / Enabled

  vars:
  - attribute_name1: PxeDev2EnDis
  - attribute_value1: Disabled
  - attribute_name2: ProcVirtualization
  - attribute_value2: Enabled

  tasks:

  # Can set more attributes as needed (or just one), then reboot at the end.

  - name: Set BIOS attribute {{attribute_name1}} to {{attribute_value1}}
    local_action: >
       redfish category=System command=SetBiosAttributes
       user={{user}} password={{password}} baseuri={{baseuri}}
       bios_attr_name={{attribute_name1}} bios_attr_value={{attribute_value1}}

  - name: Set BIOS attribute {{attribute_name2}} to {{attribute_value2}}
    local_action: >
       redfish category=System command=SetBiosAttributes
       user={{user}} password={{password}} baseuri={{baseuri}}
       bios_attr_name={{attribute_name2}} bios_attr_value={{attribute_value2}}

  - name: Create config job - reboot
    local_action: >
      redfish category=System command=CreateBiosConfigJob baseuri={{baseuri}}
      user={{user}} password={{password}}
    ignore_errors: yes
