---
- hosts: myhosts
  name: PowerEdge BIOS
  gather_facts: False

  # Commands available:
  #   GetAttributes 	Get BIOS attributes
  #   GetBootOrder 	Get device boot order
  #   SetOneTimeBoot 	Set one-time boot device

  # Note 1: not all commands implemented yet, more coming soon
  # Note 2: Pick and choose tasks as needed 

  tasks:

  - name: Prepare output file
    include: setup_outputfile.yml

  # ------------------------------------------------------------------------
  - name: Get BIOS attributes
    local_action: >
       idrac category=Bios command=GetAttributes idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes

  - name: Copy BIOS attributes to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}_bios_attributes.json

  # ------------------------------------------------------------------------
  - name: Get BIOS boot order
    local_action: >
       idrac category=Bios command=GetBootOrder idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes

  - name: Copy BIOS boot order to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}_bios_bootorder.json

  # ------------------------------------------------------------------------
  - name: Set one-time boot device to {{bootdevice}}
    local_action: >
       idrac category=Bios command=SetOneTimeBoot idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}} bootdevice={{bootdevice}}
    ignore_errors: yes

