---
- hosts: myhosts
  name: PowerEdge BIOS
  gather_facts: False

  # WARNING: CAREFULLY REVIEW ALL TASKS AVAILABLE AND SELECT WHAT YOU WANT.
  # RUNNING ALL TASKS BELOW MIGHT HAVE UNINTENDED CONSEQUENCES.

  # Commands available:
  #   GetAttributes 		Get BIOS attributes
  #   GetBootOrder 		Get device boot order
  #   SetOneTimeBoot 		Set one-time boot device
  #   SetDefaultSettings 	Set BIOS default settings 

  # Note 1: not all commands implemented yet, more coming soon
  # Note 2: Pick and choose tasks as needed 

  tasks:

  - name: Prepare output file
    include: setupoutputfile.yml
    tags:
        - bootmode

  # ------------------------------------------------------------------------
  - name: Get BIOS attributes
    local_action: >
       idrac category=Bios command=GetAttributes idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes

  - name: Copy BIOS attributes to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}_bios_attributes.json

  # ------------------------------------------------------------------------
  - name: Get BIOS boot order
    local_action: >
       idrac category=Bios command=GetBootOrder idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes

  - name: Copy BIOS boot order to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}_bios_bootorder.json

  # ------------------------------------------------------------------------
  - name: Set one-time boot device to {{bootdevice}}
    local_action: >
       idrac category=Bios command=SetOneTimeBoot idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}} bootdevice={{bootdevice}}
    ignore_errors: yes

  # ------------------------------------------------------------------------
  - name: Set default settings
    local_action: >
       idrac category=Bios command=SetDefaultSettings idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    ignore_errors: yes

  # ------------------------------------------------------------------------
  - name: Set BootMode as Uefi
    local_action: >
       idrac category=Bios command=SetAttributes bios_attributes={'BootMode':'Uefi'}
       idracuser={{idracuser}} idracpswd={{idracpswd}} idracip={{idracip}}
    tags:
        - bootmode
    ignore_errors: yes
    
  - name: Sechdule Config Job
    local_action: >
      idrac category=Bios command=ConfigJob idracuser={{idracuser}} idracpswd={{idracpswd}} idracip={{idracip}}
    tags:
        - bootmode
    ignore_errors: yes

