---
- hosts: myhosts
  name: PowerEdge iDRAC Device Firmware Inventory
  gather_facts: False

  tasks:

  - name: Prepare output file
    include: setup_outputfile.yml

  - name: Get Firmware Inventory
    local_action: >
       idrac category=Firmware command=GetInventory idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes

  - name: Copy inventory to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}_firmware_inventory.json
