---
- hosts: myhosts
  name: PowerEdge iDRAC Logs
  gather_facts: False

  # Logs available:
  #   GetSeLogs	System Event Log
  #   GetLcLogs	Lifecycle Log

  # You can use tags to run specific tasks.
  # Example: ansible-playbook get_system_logs.yml --tags=selog

  tasks:

  - name: Prepare output file
    include: setupoutputfile.yml
    tags: always

  # ------------------------------------------------------------------------
  - name: Get SE Logs
    local_action: >
       idrac category=Logs command=GetSeLogs idracip={{ idracip }}
            idracuser={{ idracuser }} idracpswd={{ idracpswd }}
    register: result
    tags: selog

  - name: Place SE Logs in file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}_SELog.json
    tags: selog

  # ------------------------------------------------------------------------
  - name: Get LC Logs
    local_action: >
       idrac category=Logs command=GetLcLogs idracip={{ idracip }}
            idracuser={{ idracuser }} idracpswd={{ idracpswd }}
    register: result
    tags: lclog

  - name: Place LC Logs in file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}_LCLog.json
    tags: lclog
