---
- hosts: myhosts
  name: PowerEdge iDRAC Get Inventory
  gather_facts: False

  # Here we define global variables, but if some servers have different
  # credentials, then place these variables in /etc/ansible/hosts to override
  # for each host
  vars:
     rootdir: /root			# where I place all results 
     idracuser: root
     idracpswd: calvin

  # Inventory/Information available:
  #   Health		Server health
  #   Model		Server model
  #   BiosVersion	BIOS version
  #   AssetTag		Asset tag
  #   Memory		System memory (GB)
  #   CPU		CPU model
  #   ConsumedWatts	Power consumed (watts)

  tasks:

  - name: Set timestamp variable
    set_fact: timestamp="{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"

  - name: Create dropoff dir for host if needed
    local_action: file path={{rootdir}}/{{host}} state=directory

  - name: Get information
    include: get_inventory.yml action={{item}}
             outfile={{rootdir}}/{{host}}/{{host}}_info_{{timestamp}}
    with_items:
      - Health
      - Model
      - BiosVersion
      - AssetTag
      - Memory
      - CPU
      - ConsumedWatts
      - PowerState
