---
- hosts: myhosts
  name: PowerEdge iDRAC
  gather_facts: False

  # Here we define global variables, but if some servers have different
  # credentials, then place these variables in /etc/ansible/hosts to override
  # for each host
  vars:
     idracuser: root
     idracpswd: calvin

  # Choices available:
  #   Health		Get server health
  #   Model		Get server model
  #   BiosVersion	Get BIOS version
  #   AssetTag		Get asset tag
  #   Memory		Get system memory (GB)
  #   CPU		Get CPU model
  #   PowerRead		Get power consumed (watts)
  #   Selog		Get SELogs

  tasks:

  - include: get_data.yml action={{item}}
    vars:
      json_file: /root/{{host}}-{{action}}
    with_items:
      - Health
      - Model
      - BiosVersion
      - AssetTag
      - Memory
      - CPU
      - PowerRead
      - Selog
