---

- hosts: myhosts
  name: PowerEdge iDRAC - Manage iDRAC Power
  gather_facts: False

  # Commands available:
  #   IdracGracefulRestarat	Restart iDRAC gracefully

  tasks:

  # ------------------------------------------------------------------------
  - name: Idrac Power graceful restart
    local_action: >
       idrac category=IdracPower command=IdracGracefulRestart
       idracip={{ idracip }} idracuser={{ idracuser }} idracpswd={{ idracpswd }}
