---
- hosts: myhosts
  name: PowerEdge iDRAC Logs
  gather_facts: False

  # Logs available:
  #   GetSelog	System Event Log
  #   GetLclog	Lifecycle Log (coming soon)

  tasks:

  - name: Prepare output file
    include: setup_outputfile.yml

  - name: Get SE Logs
    local_action: >
       idrac category=Logs command=GetSelog idracip={{ idracip }}
            idracuser={{ idracuser }} idracpswd={{ idracpswd }}
    register: result

  - name: Place SE Logs in file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}_SELog.json

  - name: Get LC Logs
    local_action: >
       idrac category=Logs command=GetLclog idracip={{ idracip }}
            idracuser={{ idracuser }} idracpswd={{ idracpswd }}
    register: result

  - name: Place LC Logs in file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}_LCLog.json
