---
- hosts: myhosts
  name: PowerEdge storage status and configuration
  gather_facts: False

  # Commands available:
  #   GetControllerStatus     Storage controller information
  #   GetDiskStatus           Disk information

  # You can use tags to run specific tasks. 
  # Example: ansible-playbook manage_storage.yml --tags=getcontrollerinfo

  tasks:

  - name: Prepare output file
    include: setupoutputfile.yml
    tags: always

  # ------------------------------------------------------------------------
  - name: Get controller information
    local_action: >
       idrac category=Storage command=GetControllerInfo idracip={{idracip}}
            idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes
    tags: getcontrollerinfo

  - name: Place data in file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}_storagecontrollers.json
    tags: getcontrollerinfo

  # ------------------------------------------------------------------------
  - name: Get disk information
    local_action: >
       idrac category=Storage command=GetDiskInfo idracip={{idracip}}
            idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes
    tags: getdiskinfo

  - name: Place data in file
    local_action: copy content={{ result | to_nice_json }}
            dest={{template}}_disks.json
    tags: getdiskinfo
