---
- hosts: myhosts
  name: PowerEdge iDRAC Manage SCP
  gather_facts: False

  # Options available:
  #   ExportSCP 	Export Server Configuration Profile (SCP)
  #   ImportSCP		Import Server Configuration Profile (SCP)

  tasks:

  - name: Export SCP file
    local_action: >
       idrac category=SCP command=ExportSCP idracip={{ idracip }}
       idracuser={{ idracuser }} idracpswd={{ idracpswd }}
       sharehost={{ sharehost }} sharename={{ sharename }}
       shareuser={{ shareuser }} sharepswd={{ sharepswd }}
       hostname={{ host }}

  - name: Import SCP file
    local_action: >
       idrac category=SCP command=ImportSCP idracip={{ idracip }}
       idracuser={{ idracuser }} idracpswd={{ idracpswd }}
       sharehost={{ sharehost }} sharename={{ sharename }}
       shareuser={{ shareuser }} sharepswd={{ sharepswd }}
       hostname={{ host }}
