---
- hosts: myhosts
  name: PowerEdge iDRAC Get System Inventory
  gather_facts: False

  tasks:

  - name: Prepare output file
    include: setupoutputfile.yml

  - name: Getting system inventory
    local_action: >
       idrac category=Inventory command=GetInventory idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result

  - name: Copying results to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}_inventory.json
