---
- hosts: myhosts
  name: PowerEdge storage status and configuration
  gather_facts: False

  # Commands available:
  #   GetControllerStatus     Storage controller information
  #   GetDiskStatus           Disk information

  tasks:

  - name: Prepare output file
    include: setup_outputfile.yml

  # ------------------------------------------------------------------------
  - name: Get controller information
    local_action: >
       idrac category=Storage command=GetControllerInfo idracip={{idracip}}
            idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes

  - name: Place data in file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}_storagecontrollers.json

  # ------------------------------------------------------------------------
  - name: Get disk information
    local_action: >
       idrac category=Storage command=GetDiskInfo idracip={{idracip}}
            idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes

  - name: Place data in file
    local_action: copy content={{ result | to_nice_json }}
            dest={{template}}_disks.json
