---
- hosts: myhosts
  name: PowerEdge iDRAC Get System Inventory
  gather_facts: False

  tasks:

  - name: Prepare output file
    include: setup_outputfile.yml

  - local_action: >
       idrac category=Inventory command=GetInventory idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result

  - local_action: copy content={{ result | to_nice_json }}
       dest={{template}}_inventory.json
