---

- hosts: myhosts
  name: PowerEdge iDRAC Manage Users
  gather_facts: False

  # Options available:
  #   ListUsers			Lists all users, including empty slots
  #   AddUser			Add user
  #   EnableUser		Enable user
  #   DiasbleUser		Disable user
  #   UpdateUserRole		Update user role
  #   UpdateUserPassword	Update user password
  #   DeleteUser		Delete user - Coming Soon

  tasks:

  # Though some tasks are not mutually exclusive, do only one task at a time

  # ------------------------------------------------------------------------
  - name: Prepare output file
    include: setup_outputfile.yml

  - name: List all iDRAC users
    local_action: >
       idrac category=Users command=ListUsers idracip={{ idracip }}
       idracuser={{ idracuser }} idracpswd={{ idracpswd }} 
    register: result

  - local_action: copy content={{ result | to_nice_json }}
       dest={{template}}_idrac_users.json

  # Select the actions you want to execute, comment out the rest

  # ------------------------------------------------------------------------
  - name: Add iDRAC user
    local_action: >
       idrac category=Users command=AddUser idracip={{ idracip }}
       idracuser={{ idracuser }} idracpswd={{ idracpswd }} userid={{ userid }}
       username={{ username }} userpswd={{ userpswd }} userrole={{ userrole }}

  # ------------------------------------------------------------------------
  - name: Update iDRAC user role
    local_action: >
       idrac category=Users command=UpdateUserRole idracip={{ idracip }}
       idracuser={{ idracuser }} idracpswd={{ idracpswd }} userid={{ userid }}
       userrole={{ userrole }}

  # ------------------------------------------------------------------------
  - name: Update iDRAC user password
    local_action: >
       idrac category=Users command=UpdateUserPassword idracip={{ idracip }}
       idracuser={{ idracuser }} idracpswd={{ idracpswd }} userid={{ userid }}
       userpswd={{ userpswd }}

  # ------------------------------------------------------------------------
  # Not yet implemented
  - name: Delete iDRAC user
    local_action: >
       idrac category=Users command=DeleteUser idracip={{ idracip }}
       idracuser={{ idracuser }} idracpswd={{ idracpswd }} userid={{ userid }}

