---
- hosts: myhosts
  connection: local
  name: Add User
  gather_facts: False

  # User to add, modify or delete is defined in file group_vars/all

  tasks:

  # When adding a user, you must enable it afterwards
  - name: Add user
    redfish:
      category: Accounts
      command: AddUser
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
      userid: "{{ userid }}"
      username: "{{ username }}"
      userpswd: "{{ userpswd }}"
      userrole: "{{ userrole }}"

  - name: Enable user
    redfish:
      category: Accounts
      command: EnableUser
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
      userid: "{{ userid }}"
