---
- hosts: myhosts
  connection: local
  name: Disable User
  gather_facts: False

  # User to add, modify or delete is defined in file group_vars/all

  tasks:

  - name: Disable user
    redfish_command:
      category: Accounts
      command: DisableUser
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
      userid: "{{ userid }}"
