---
- hosts: myhosts
  connection: local
  name: Enable User
  gather_facts: False

  # User to add, modify or delete is defined in file group_vars/myhosts

  tasks:

  - name: Enable user
    redfish:
      category: Accounts
      command: EnableUser
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
      userid: "{{ userid }}"
