---
- hosts: myhosts
  connection: local
  name: Update user password
  gather_facts: False

  # User to add, modify or delete is defined in file group_vars/all

  tasks:

  - name: Update user password
    redfish_command:
      category: Accounts
      command: UpdateUserPassword
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
      userid: "{{ userid }}"
      userpswd: "{{ userpswd }}"
