---
- hosts: myhosts
  connection: local
  name: Restart Manager
  gather_facts: False

  tasks:

  - name: Manager graceful restart
    redfish:
      category: Manager
      command: GracefulRestart
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
