---
- hosts: myhosts
  connection: local
  name: Set Manager NTP settings
  gather_facts: False

  vars:
    - ntpserver1: ntp.domain.com

  tasks:

  - name: Enable NTP
    redfish:
      category: Manager
      command: SetAttributes
      mgr_attr_name: NTPConfigGroup.1.NTPEnable
      mgr_attr_value: Enabled
      baseuri: "{{ baseuri }}"
      user: "{{ user}}"
      password: "{{ password }}"

  - name: Set NTP server 1 to {{ ntpserver1 }}
    redfish:
      category: Manager
      command: SetAttributes
      mgr_attr_name: NTPConfigGroup.1.NTP1
      mgr_attr_value: "{{ ntpserver1 }}"
      baseuri: "{{ baseuri }}"
      user: "{{ user}}"
      password: "{{ password }}"

  # Add more NTP servers as needed
  # To get exact attributes names, run the getattributes task first
