---
- hosts: myhosts
  connection: local
  name: Set Manager VLAN ID settings
  gather_facts: False

  vars:
    - vlanid: 1

  tasks:

  - name: Enable VLAN ID
    redfish:
      category: Manager
      command: SetAttributes
      mgr_attr_name: NIC.1.VLanEnable
      mgr_attr_value: Enabled
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"

  - name: Set VLAN ID
    redfish:
      category: Manager
      command: SetAttributes
      mgr_attr_name: NIC.1.VLanID
      mgr_attr_value: "{{ vlanid }}"
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
