---
- hosts: myhosts
  connection: local
  name: Manage System Power - Greaceful restart
  gather_facts: False

  tasks:

  - name: Graceful system power restart
    redfish:
      category: System
      command: PowerGracefulRestart
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
