---
- hosts: myhosts
  connection: local
  name: Manage System Power - Force Off
  gather_facts: False

  tasks:

  - name: Turn system power off
    redfish:
      category: System
      command: PowerForceOff
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
