---
- hosts: myhosts
  connection: local
  name: Manage System Power - Graceful shutdown
  gather_facts: False

  tasks:

  - name: Graceful system power shutdown
    redfish:
      category: System
      command: PowerGracefulShutdown
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
