---
- hosts: myhosts
  connection: local
  name: Manage System Power - Turn on
  gather_facts: False

  tasks:

  - name: Turn system power on
    redfish:
      category: System
      command: PowerOn
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
