---
- hosts: myhosts
  connection: local
  name: Clear System Logs
  gather_facts: False

  tasks:

  - name: Clear Logs
    redfish:
      category: Manager
      command: ClearLogs
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
