---
- hosts: myhosts
  name: PowerEdge iDRAC NIC Inventory
  gather_facts: False

  tasks:

  - name: Prepare output file
    include: setupoutputfile.yml

  - name: Get NIC Inventory
    local_action: >
       idrac category=Inventory command=GetNICInventory idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes

  - name: Copy inventory to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}_nic_inventory.json
