---
- hosts: myhosts
  name: PowerEdge iDRAC Power Supply (PSU) Inventory
  gather_facts: False

  tasks:

  # Not supported in 12G servers

  - name: Set output file
    include: set_output_file.yml type=PSUInventory

  - name: Get PSU Inventory
    local_action: >
       idrac category=Inventory command=GetPSUInventory idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes

  - name: Copy information to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
