---
- hosts: myhosts
  connection: local
  name: Get storage controller inventory
  gather_facts: False

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml type=StorageControllerInventory

  - name: Get storage controller inventory
    redfish:
      category: Inventory
      command: GetStorageControllerInventory
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
