---
- hosts: myhosts
  connection: local
  name: Get System Logs
  gather_facts: False

  vars:
    category: Logs

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get System Logs
    redfish:
      category: Manager
      command: GetLogs
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
