---
- hosts: myhosts
  name: NIC Inventory
  gather_facts: False

  tasks:

  - name: Define output file
    include: set_output_file.yml type=NicInventory

  - name: Get NIC Information
    local_action: >
       redfish category=Inventory command=GetNicInventory baseuri={{baseuri}}
       login={{login}} password={{password}}
    register: result
    ignore_errors: yes

  - name: Copy information to output file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
