---
- hosts: myhosts
  name: PowerEdge storage inventory
  gather_facts: False

  # Commands available:
  #   GetControllerInventory   Storage controller inventory
  #   GetDiskInventory         Disk inventory

  tasks:

  # ------------------------------------------------------------------------
  - name: Set output file
    include: set_output_file.yml type=StorageControllerInventory
    tags: getcontrollerinventory

  - name: Get storage controller inventory
    local_action: >
       idrac category=Storage command=GetControllerInventory idracip={{idracip}}
            idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes
    tags: getcontrollerinventory

  - name: Place data in file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}.json
    tags: getcontrollerinventory

  # ------------------------------------------------------------------------
  - name: Set output file
    include: set_output_file.yml type=DiskInventory
    tags: getdiskinventory

  - name: Get disk inventory
    local_action: >
       idrac category=Storage command=GetDiskInventory idracip={{idracip}}
            idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes
    tags: getdiskinventory

  - name: Place data in file
    local_action: copy content={{ result | to_nice_json }}
            dest={{template}}.json
    tags: getdiskinventory
