---
- hosts: myhosts
  name: PowerEdge iDRAC Get System Inventory
  gather_facts: False

  tasks:

  - name: Define output file
    include: set_output_file.yml type=SystemInventory

  - name: Getting system inventory
    local_action: >
       idrac category=Inventory command=GetSystemInventory idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result

  - name: Copy results to output file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
