---
- hosts: myhosts
  name: Get System Logs
  gather_facts: False

  # Example:
  # ansible-playbook get_system_logs.yml

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml type=Logs

  - name: Get System Logs
    local_action: >
       redfish category=Manager command=GetLogs baseuri={{ baseuri }}
            user={{ user }} password={{ password }}
    register: result

  - name: Copy Logs to output file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}.json
