---
- hosts: myhosts
  connection: local
  name: NIC Inventory
  gather_facts: False

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml type=NicInventory

  - name: Get NIC Information
    redfish:
      category: Inventory
      command: GetNicInventory
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
    register: result
    ignore_errors: yes

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
