---
- hosts: myhosts
  name: Storage inventory
  gather_facts: False

  # You can use tags to run specific tasks.
  #
  # Examples:
  # ansible-playbook manage_bios.yml --tags getcontrollerinventory
  # ansible-playbook manage_bios.yml --tags getdiskinventory

  # Commands available:
  #   GetControllerInventory   Get Storage controller inventory
  #   GetDiskInventory         Get Disk inventory

  tasks:

  # --- Get Storage Controller Inventory -----------------------------------
  - name: Define output file
    include_tasks: set_output_file.yml type=StorageControllerInventory
    tags: getcontrollerinventory

  - name: Get storage controller inventory
    local_action: >
       redfish category=Storage command=GetControllerInventory baseuri={{baseuri}}
            user={{user}} password={{password}}
    register: result
    ignore_errors: yes
    tags: getcontrollerinventory

  - name: Copy results to output file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}.json
    tags: getcontrollerinventory

  # --- Get Disk Inventory -------------------------------------------------
  - name: Define output file
    include_tasks: set_output_file.yml type=DiskInventory
    tags: getdiskinventory

  - name: Get disk inventory
    local_action: >
       redfish category=Storage command=GetDiskInventory baseuri={{baseuri}}
            user={{user}} password={{password}}
    register: result
    ignore_errors: yes
    tags: getdiskinventory

  - name: Copy results to output file
    local_action: copy content={{ result | to_nice_json }}
            dest={{template}}.json
    tags: getdiskinventory
