---
- hosts: myhosts
  connection: local
  name: Get disk inventory
  gather_facts: False

  vars:
    category: DiskInventory

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get disk inventory
    redfish:
      category: Inventory
      command: GetDiskInventory
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
