---
- hosts: myhosts
  name: System Logs
  gather_facts: False

  # You can use tags to run specific tasks.
  #
  # Examples:
  # ansible-playbook get_system_logs.yml --tags selogs
  # ansible-playbook get_system_logs.yml --tags lclogs

  # Commands available:
  #   GetSELogs		Get System Event Logs
  #   GetLCLogs		Get Lifecycle Logs

  tasks:

  # --- Get SE Logs --------------------------------------------------------
  - name: Define output file
    include_tasks: set_output_file.yml type=SELogs
    tags: selogs

  - name: Get SE Logs
    local_action: >
       redfish category=Logs command=GetSELogs baseuri={{ baseuri }}
            user={{ user }} password={{ password }}
    register: result
    tags: selogs

  - name: Copy SE Logs to output file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}.json
    tags: selogs

  # --- Get LC Logs --------------------------------------------------------
  - name: Define output file
    include_tasks: set_output_file.yml type=LCLogs
    tags: lclogs

  - name: Get LC Logs
    local_action: >
       redfish category=Logs command=GetLCLogs baseuri={{ baseuri }}
            user={{ user }} password={{ password }}
    register: result
    tags: lclogs

  - name: Copy LC Logs to output file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}.json
    tags: lclogs
