---
- hosts: myhosts
  name: PowerEdge iDRAC Logs
  gather_facts: False

  # Logs available:
  #   GetSeLogs	System Event Log
  #   GetLcLogs	Lifecycle Log

  # You can use tags to run specific tasks.
  # Example: ansible-playbook get_system_logs.yml --tags=selog

  tasks:

  # ------------------------------------------------------------------------
  - name: Set output file
    include: set_output_file.yml type=SELogs
    tags: selogs

  - name: Get SE Logs
    local_action: >
       idrac category=Logs command=GetSELogs idracip={{ idracip }}
            idracuser={{ idracuser }} idracpswd={{ idracpswd }}
    register: result
    tags: selogs

  - name: Place SE Logs in file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}.json
    tags: selogs

  # ------------------------------------------------------------------------
  - name: Set output file
    include: set_output_file.yml type=LCLogs
    tags: lclogs

  - name: Get LC Logs
    local_action: >
       idrac category=Logs command=GetLCLogs idracip={{ idracip }}
            idracuser={{ idracuser }} idracpswd={{ idracpswd }}
    register: result
    tags: lclogs

  - name: Place LC Logs in file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}.json
    tags: lclogs
