---
- hosts: myhosts
  connection: local
  name: Fan Inventory
  gather_facts: False

  tasks:

  - name: Set output file
    include_tasks: create_output_file.yml type=FanInventory

  - name: Get fans statistics
    redfish:
      category: Inventory
      command: GetFanInventory
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
    register: result
    ignore_errors: yes

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
