---
- hosts: myhosts
  connection: local
  name: System Inventory
  gather_facts: False

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml type=SystemInventory

  - name: Getting system inventory
    redfish:
      category: Inventory
      command: GetSystemInventory
      baseuri: "{{ baseuri }}"
      user: "{{ user }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result | to_nice_json }}"
      dest: "{{ template }}.json"
