---
- hosts: myhosts
  name: PowerEdge iDRAC NIC Inventory
  gather_facts: False

  tasks:

  - name: Set output file
    include: set_output_file.yml type=NICInventory

  - name: Get NIC Information
    local_action: >
       idrac category=Network command=GetNICInventory idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes

  - name: Copy information to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
