---
- hosts: myhosts
  name: PowerEdge iDRAC Power Supply (PSU) Information
  gather_facts: False

  tasks:

  - name: Prepare output file
    include: setupoutputfile.yml

  - name: Get PSU Information
    local_action: >
       idrac category=Inventory command=GetPSUInventory idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes

  - name: Copy information to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}_psu_inventory.json
