---
- hosts: myhosts
  name: PowerEdge iDRAC Logs
  gather_facts: False

  # You can use tags to run specific tasks.
  #
  # Examples:
  # ansible-playbook get_system_logs.yml --tags selogs
  # ansible-playbook get_system_logs.yml --tags lclogs

  # Commands available:
  #   GetSELogs		Get System Event Logs
  #   GetLCLogs		Get Lifecycle Logs

  tasks:

  # --- Get SE Logs --------------------------------------------------------
  - name: Define output file
    include: set_output_file.yml type=SELogs
    tags: selogs

  - name: Get SE Logs
    local_action: >
       idrac category=Logs command=GetSELogs idracip={{ idracip }}
            idracuser={{ idracuser }} idracpswd={{ idracpswd }}
    register: result
    tags: selogs

  - name: Copy SE Logs to output file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}.json
    tags: selogs

  # --- Get LC Logs --------------------------------------------------------
  - name: Define output file
    include: set_output_file.yml type=LCLogs
    tags: lclogs

  - name: Get LC Logs
    local_action: >
       idrac category=Logs command=GetLCLogs idracip={{ idracip }}
            idracuser={{ idracuser }} idracpswd={{ idracpswd }}
    register: result
    tags: lclogs

  - name: Copy LC Logs to output file
    local_action: copy content={{ result | to_nice_json }}
             dest={{template}}.json
    tags: lclogs
