---
- hosts: myhosts
  name: PowerEdge BIOS
  gather_facts: False

  # WARNING: CAREFULLY REVIEW ALL TASKS AVAILABLE AND SELECT WHAT YOU WANT.
  # RUNNING ALL TASKS BELOW WILL HAVE UNINTENDED CONSEQUENCES.

  # Commands available:
  #   GetAttributes 		Get BIOS attributes
  #   GetBootOrder 		Get device boot order
  #   SetOneTimeBoot 		Set one-time boot device
  #   SetDefaultSettings 	Set BIOS default settings 
  #   SetAttributes		Set BIOS attributes
  #   ConfigJob			Implement new settings

  # You can use tags to run specific tasks. 
  # Example: ansible-playbook manage_bios.yml --tags=getattributes

  tasks:

  # ------------------------------------------------------------------------
  - name: Set output file
    include: set_output_file.yml type=BiosAttributes
    tags: getattributes

  - name: Get BIOS attributes
    local_action: >
       idrac category=Bios command=GetAttributes idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes
    tags: getattributes

  - name: Copy BIOS attributes to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
    tags: getattributes

  # ------------------------------------------------------------------------
  - name: Set output file
    include: set_output_file.yml type=BiosBootOrder
    tags: getbootorder

  - name: Get BIOS boot order
    local_action: >
       idrac category=Bios command=GetBootOrder idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes
    tags: getbootorder

  - name: Copy BIOS boot order to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
    tags: getbootorder

  # ------------------------------------------------------------------------
  - name: Set one-time boot device to {{bootdevice}}
    local_action: >
       idrac category=Bios command=SetOneTimeBoot idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}} bootdevice={{bootdevice}}
    ignore_errors: yes
    tags: setonetimebootdevice

  # ------------------------------------------------------------------------
  - name: Set default settings
    local_action: >
       idrac category=Bios command=SetDefaultSettings idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    ignore_errors: yes
    tags: setdefaultsettings

  # ------------------------------------------------------------------------
  - name: Set BootMode to UEFI
    local_action: >
       idrac category=Bios command=SetAttributes bios_attributes={'BootMode':'Uefi'}
       idracuser={{idracuser}} idracpswd={{idracpswd}} idracip={{idracip}}
    tags: bootmodeuefi
    ignore_errors: yes
    
  - name: Schedule Config Job
    local_action: >
      idrac category=Bios command=ConfigJob idracip={{idracip}}
      idracuser={{idracuser}} idracpswd={{idracpswd}}
    tags: bootmodeuefi
    ignore_errors: yes

  # ------------------------------------------------------------------------
  - name: Set BootMode to Legacy BIOS
    local_action: >
       idrac category=Bios command=SetAttributes bios_attributes={'BootMode':'Bios'}
       idracuser={{idracuser}} idracpswd={{idracpswd}} idracip={{idracip}}
    tags: bootmodelegacybios
    ignore_errors: yes
    
  # Reboots server
  - name: Schedule Config Job
    local_action: >
      idrac category=Bios command=ConfigJob idracip={{idracip}}
      idracuser={{idracuser}} idracpswd={{idracpswd}}
    tags: bootmodelegacybios
    ignore_errors: yes
