---

- hosts: myhosts
  name: PowerEdge iDRAC - Manage iDRAC Settings
  gather_facts: False

  # WARNING: CAREFULLY REVIEW ALL TASKS AVAILABLE AND SELECT WHAT YOU WANT.
  # RUNNING ALL TASKS BELOW MIGHT HAVE UNINTENDED CONSEQUENCES.
  # ALTERNATIVELY, USE TAGS:
  # Example: ansible-playbook manage_idrac_settings.yml --tags=settimezone

  # Commands available:
  #   GetAttributes		Get iDRAC attributes
  #   SetDefaultSettings	Set iDRAC default settings
  #   SetAttributes		Most settings can be set using this
  #   ViewJobQueue		View Job Queue (coming soon)

  tasks:

  # ------------------------------------------------------------------------
  # 14G only
  - name: Set output file
    include: set_output_file.yml type=IdracAttributes
    tags: getattributes

  - name: Get iDRAC attributes
    local_action: >
       idrac category=Idrac command=GetAttributes idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes
    tags: getattributes

  - name: Copy iDRAC attributes to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}.json
    tags: getattributes

  # ------------------------------------------------------------------------
  # 14G only
  - name: Set Timezone
    local_action: >
       idrac category=Idrac command=SetAttributes
       idrac_attributes={'Time.1.Timezone':'US/Central'}
       idracuser={{idracuser}} idracpswd={{idracpswd}} idracip={{idracip}}
    tags: settimezone
    ignore_errors: yes

  # ------------------------------------------------------------------------
  # 14G only
  - name: Enable NTP
    local_action: >
       idrac category=Idrac command=SetAttributes
       idrac_attributes={'NTPConfigGroup.1.NTPEnable':'Enabled'}
       idracuser={{idracuser}} idracpswd={{idracpswd}} idracip={{idracip}}
    tags: setntp
    ignore_errors: yes

  - name: Set NTP server
    local_action: >
       idrac category=Idrac command=SetAttributes
       idrac_attributes={'NTPConfigGroup.1.NTP1':'ntp.server.com'}
       idracuser={{idracuser}} idracpswd={{idracpswd}} idracip={{idracip}}
    tags: setntp
    ignore_errors: yes

  # Add more NTP servers as needed
  # To get exact attributes names, run the getattributes task first

  # ------------------------------------------------------------------------
  # Resetting to default values will reset everything and reboot the iDRAC
  - name: Idrac set default settings
    local_action: >
       idrac category=Idrac command=SetDefaultSettings
       idracip={{idracip}} idracuser={{idracuser}} idracpswd={{idracpswd}}
    tags: setdefaultsettings

