---
- hosts: myhosts
  name: Manage NICs
  gather_facts: False

  # Carefully review all tasks and select what you need by using tags.
  # Running *ALL* tasks will have unintended consequences!
  #
  # Updating BIOS settings requires creating a configuration job to implement
  # (which then reboots the system), so pass the 'createbiosconfigjob' tag 
  # accordingly.
  #
  # Examples:
  # ansible-playbook manage_nics.yml --tags enablepxenic2
  # ansible-playbook manage_nics.yml --tags "disablepxenic1,createbiosconfigjob"

  tasks:

  # ------------------------------------------------------------------------
  - name: Enable PXE Boot for NIC1
    local_action: >
       redfish category=System command=SetBiosAttributes
       user={{user}} password={{password}} baseuri={{baseuri}}
       bios_attr_name=PxeDev1EnDis bios_attr_value=Enabled
    tags: enablepxenic1
    ignore_errors: yes
    
  - name: Disable PXE Boot for NIC1
    local_action: >
       redfish category=System command=SetBiosAttributes
       user={{user}} password={{password}} baseuri={{baseuri}}
       bios_attr_name=PxeDev1EnDis bios_attr_value=Disabled
    tags: disablepxenic1
    ignore_errors: yes
    
  # ------------------------------------------------------------------------
  - name: Enable PXE Boot for NIC2
    local_action: >
       redfish category=System command=SetBiosAttributes
       user={{user}} password={{password}} baseuri={{baseuri}}
       bios_attr_name=PxeDev2EnDis bios_attr_value=Enabled
    tags: enablepxenic2
    ignore_errors: yes
    
  - name: Disable PXE Boot for NIC2
    local_action: >
       redfish category=System command=SetBiosAttributes
       user={{user}} password={{password}} baseuri={{baseuri}}
       bios_attr_name=PxeDev2EnDis bios_attr_value=Disabled
    tags: disablepxenic2
    ignore_errors: yes
    
  # ------------------------------------------------------------------------
  - name: Schedule Config Job - reboot
    local_action: >
      redfish category=System command=CreateBiosConfigJob baseuri={{baseuri}}
      user={{user}} password={{password}}
    tags: createbiosconfigjob
    ignore_errors: yes

