---
- hosts: myhosts
  name: PowerEdge Cooling Information
  gather_facts: False

  # Commands available:
  #   GetFanStats 		Get fans statistics

  # You can use tags to run specific tasks. 
  # Example: ansible-playbook manage_cooling.yml --tags=getfanstats

  tasks:

  - name: Prepare output file
    include: setupoutputfile.yml
    tags: [getfanstats]

  # ------------------------------------------------------------------------
  - name: Get fans statistics
    local_action: >
       idrac category=Cooling command=GetFanStats idracip={{idracip}}
       idracuser={{idracuser}} idracpswd={{idracpswd}}
    register: result
    ignore_errors: yes
    tags: getfanstats

  - name: Copy fans statistics to file
    local_action: copy content={{ result | to_nice_json }}
       dest={{template}}_fans_reading.json
    tags: getfanstats

