---

- hosts: myhosts
  name: PowerEdge iDRAC - Manage iDRAC Power
  gather_facts: False

  # I AM PLACING THIS TASK IN A SEPARATE PLAYOOK TO AVOID ACCIDENTAL IDRAC
  # REBOOTS.

  # Commands available:
  #   GracefulRestart		Restart iDRAC gracefully

  tasks:

  # ------------------------------------------------------------------------
  - name: Idrac Power graceful restart
    local_action: >
       idrac category=Idrac command=GracefulRestart
       idracip={{ idracip }} idracuser={{ idracuser }} idracpswd={{ idracpswd }}
