---
- hosts: myhosts
  name: Firmware Update
  gather_facts: False

  tasks:
  - name: download Catalog file
    get_url:
        url: http://downloads.dell.com/catalog/Catalog.xml.gz
        dest: /tmp/Catalog.gz
        mode: 0444
        force: yes
    register: CatalogFile
    delegate_to: 127.0.0.1
    run_once: true

  - name: extract Catalog file
    shell: gzip -d /tmp/Catalog.gz -f
    delegate_to: 127.0.0.1
    run_once: true

  - name: create folder to download firmware binary
    file:
        path: /tmp/firmware
        state: directory
        mode: 0755
    delegate_to: 127.0.0.1
    run_once: true

  - name: Evaluate if firmware needs to be updated
    local_action: >
        redfish category=Update command=EvaluateFirmwareUpgrade baseuri={{baseuri}}
        user={{user}} password={{password}}
    register: firmware

  # Will only download firmware image if an upgrade is available
  - name: download firmware images to local disk
    get_url:
        url: http://downloads.dell.com/{{ item.path }}
        dest: /tmp/firmware/{{ item.path | basename}}
        mode: 0444
        force: no
    when:
        - item.latest != item.curr
    with_items:
        - "{{firmware.result.Firmwares}}"
    delegate_to: 127.0.0.1

  # Will only upload firmware image if an upgrade is available
  - name: upload firmware images to OOB controller
    local_action: >
        redfish category=Update command=UploadFirmware baseuri={{baseuri}}
        user={{user}} password={{password}}
        FWPath=/tmp/firmware/{{ item.path | basename}}
    register: fw_available
    when:
        - item.latest != item.curr
    with_items:
        - "{{firmware.result.Firmwares}}"
    ignore_errors: yes

  - set_fact:
      schedule_fw_update_job: True
    when: item.result is defined
    with_items:
      - "{{fw_available.results}}"

  # Will only install firmware image if an upgrade is available
  - name: install firmware image
    local_action: >
        redfish category=Update command=ScheduleUpdate baseuri={{baseuri}}
        user={{user}} password={{password}}
        InstallOption=NowAndReboot
    when: schedule_fw_update_job is defined
